# Stage 1: Build stage
FROM debian:bullseye AS builder

WORKDIR /app

RUN \
  apt-get update -y && \
  apt-get install -y build-essential \
  curl \
  libnuma-dev \
  zlib1g-dev \
  libgmp-dev \
  libgmp10 \
  git \
  wget \
  lsb-release \
  software-properties-common \
  gnupg2 \
  apt-transport-https \
  gcc \
  autoconf \
  automake \
  pkg-config

RUN \
  curl https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup -o /usr/bin/ghcup && \
  chmod +x /usr/bin/ghcup

ARG GHC=9.4.8
ARG CABAL=3.10

RUN \
  ghcup -v install ghc --isolate /usr/local --force ${GHC} && \
  ghcup -v install cabal --isolate /usr/local/bin --force ${CABAL}

ENV PATH="/usr/local/bin:/usr/local/bin/ghc-${GHC}/bin:/usr/local/bin/cabal-${CABAL}/bin:${PATH}"

RUN cabal update

COPY . .

RUN cabal install --dependencies-only --installdir=/app

RUN cabal build

RUN cabal install --installdir=/app exe:chemist-preprocessor

# Stage 2: Runtime stage
FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/chemist-preprocessor /app/chemist-preprocessor
COPY .env /app/.env

RUN chmod +x /app/chemist-preprocessor

RUN apt-get update && \
  apt-get install -y libnuma1 libgmp10 && \
  apt-get autoremove -y && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["/app/chemist-preprocessor"]